services:
  - type: web
    name: igbo-community-canberra
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: DATABASE_URL
        value: postgresql://icc_app.tjmiptvqmwnzxuzadhxl:IgboCommCBR2026!@aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres
      - key: NEXTAUTH_SECRET
        value: igbo-community-canberra-secret-2026-change-this
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://tjmiptvqmwnzxuzadhxl.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqbWlwdHZxbXduenh1emFkaHhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA1OTMwNTUsImV4cCI6MjEwNjE2OTA1NX0.qt0beQ3wzsf3M4GTHp3sr3ZopW0y_vVXoUtwLQfAqII
